version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: babilonia_app
    env_file:
      - ../.env.dev
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ..:/app

  db:
    image: postgres:15
    container_name: babilonia_db
    environment:
      POSTGRES_USER: babilonia
      POSTGRES_PASSWORD: babilonia
      POSTGRES_DB: babilonia_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
